// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKuO8AwiSAD-wr_R4X0UT56VfDa0-3w64',
    appId: '1:89908921445:android:2760c9226408e9b2c3728c',
    messagingSenderId: '89908921445',
    projectId: 'flutter-auth-new',
    storageBucket: 'flutter-auth-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC03v3rTLYOo2XhL_aK6mJAIo9yZpmY_9k',
    appId: '1:89908921445:ios:13b457e2cf94a92dc3728c',
    messagingSenderId: '89908921445',
    projectId: 'flutter-auth-new',
    storageBucket: 'flutter-auth-new.appspot.com',
    androidClientId: '89908921445-6rc4971ku8g53o8mlk85vh7bf8f5p6c7.apps.googleusercontent.com',
    iosClientId: '89908921445-uh7hvmlt8kl9r68dek9dmfmqprirjb3r.apps.googleusercontent.com',
    iosBundleId: 'com.tinyappsteam.flutterFirestore',
  );
}
